import 'source-map-support/register'
import AristonAPI, {
  type APISettings,
  type Logger,
  type SettingManager,
} from './lib/AristonAPI'
import {
  type BaseGetData,
  type BasePlantData,
  type BasePostSettings,
  type BasePostSettingsWithOld,
  type Data,
  type GetDataFailure,
  type GetDataSuccess,
  type GetDataWithSettingsSuccess,
  type GetSettings,
  type HistogramData,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  Mode,
  OperationMode,
  type Plant,
  type PlantData,
  type PlantHeader,
  type PlantSettings,
  type PostData,
  type PostPlantData,
  type PostSettings,
  type ReportData,
  Switch,
  type ViewModel,
  WheType,
} from './types'

export {
  AristonAPI as default,
  Mode,
  OperationMode,
  Switch,
  WheType,
  type APISettings,
  type BaseGetData,
  type BasePlantData,
  type BasePostSettings,
  type BasePostSettingsWithOld,
  type Data,
  type GetDataFailure,
  type GetDataSuccess,
  type GetDataWithSettingsSuccess,
  type GetSettings,
  type HistogramData,
  type Logger,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  type Plant,
  type PlantData,
  type PlantHeader,
  type PlantSettings,
  type PostPlantData,
  type PostData,
  type PostSettings,
  type ReportData,
  type SettingManager,
  type ViewModel,
}
