import 'source-map-support/register'
import AristonAPI, {
  type APISettings,
  type Logger,
  type SettingManager,
} from './lib/AristonAPI'
import {
  type BaseData,
  type BaseGetData,
  type BasePostSettings,
  type BasePostSettingsWithOld,
  type GetData,
  type GetDataWithSettings,
  type GetSettings,
  type HistogramData,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  Mode,
  OperationMode,
  type Plant,
  type PlantData,
  type PlantHeader,
  type PlantSettings,
  type PostData,
  type PostPlantData,
  type PostSettings,
  type ReportData,
  Switch,
  type ViewModel,
  WheType,
} from './types'

export {
  AristonAPI as default,
  Mode,
  OperationMode,
  Switch,
  WheType,
  type APISettings,
  type BaseData,
  type BaseGetData,
  type BasePostSettings,
  type BasePostSettingsWithOld,
  type GetData,
  type GetDataWithSettings,
  type GetSettings,
  type HistogramData,
  type Logger,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  type Plant,
  type PlantData,
  type PlantHeader,
  type PlantSettings,
  type PostPlantData,
  type PostData,
  type PostSettings,
  type ReportData,
  type SettingManager,
  type ViewModel,
}
